### ISSUE TITLE
Y-Scale memory used

### ISSUE THREAD

**Issue by Lubbows** [rybafish/rybafish#562] opened 2022-01-19 13:13 UTC
Add possibility to change manually the Y-Scale for the memory used (for example).

Currently, the Y-Scale is automatically set, but we cannot set the minimum Y-Scale. The minimum value = maximum value / 10

This feature could be help us to detect some lower variation on the memory, which is not possible when we have a big amount of memory.

Thank you for this tools!

**Comment by rybafish** [comment] 2022-01-19 19:48
You are right, zero is kinda hard coded minimum value for all KPIs...

I never needed this functionality but I tried to implement as I understand it.

The interface is not very friendly, but here how it works. Lets say we have "Used Memory" with max value 2900 GB. Automatically calculated YRange will be 3000 GB. If you double-click on this value in KPIs table - you can change it.

You can set one value, or range, for example: 2800-3000. In this case 0 on the screen will be 2800 GB.

Please try to use it and let me know if it does what is expected. Secret build link [here](https://github.com/rybafish/rybafish/releases/download/untagged-7f0656a14aa68fe8619e/RybaFish_09betaXI_YScaleRange.7z). There was a high number of changes in chart render area, please pay attention if the chart displayed correctly and values match actual data.

P.S. 300 / 3000 means that maximum on the screen is 3000 and one vertical Y mark is 300 GB. Zero was always zero. Now if you set a range, YScale will be "20 / 2800-3000" which means: range on the screen is from 2800 to 3000, every vertical line is 20 GB.

**Comment by Lubbows** [comment] 2022-01-19 20:55
Many thanks @rybafish! You're fully understand what I imagined!

The link seems to be broken (404 not found), but once downloaded, I'll keep you in touch with this version, but I'm sure that it will works fine as you explained.

Thank you again!

**Comment by rybafish** [comment] 2022-01-19 20:58
sorry, try this temporal one: https://github.com/rybafish/rybafish/releases/download/tmp/RybaFish_09betaXI_YScaleRange.7z

**Comment by Lubbows** [comment] 2022-01-20 08:10
On my side, all KPIs in the indexserver service don't no longer show data, the columns Y-Scale, Unit, Max, Average, Last, stay empty and the chart too. This issue is not present for your last beta (2021-12-23) published on your site, 

I'm staying available to help you,

**Comment by rybafish** [comment] 2022-01-20 08:48
Looks the problem is in my technical config, please replace it with your one, sorry for that.

**Comment by Lubbows** [comment] 2022-01-20 09:03
It works fine! Many thanks

**Comment by rybafish** [comment] 2022-01-20 09:10
Okay good, if all goes fine - will be included in master branch

**Closed by rybafish** 2022-01-20 09:10 UTC
Labels: enhancement, chart
